truths = ["After you've dropped a piece of food, what's the longest time you've left it on the ground and then ate it?",
"Are you a hard-working student?",
"Are you into any sports?",
"Are you scared of any animals?",
"Are you scared of dying? Why?",
"Are you scared of ghosts?",
"Are you scared of the dark?",
"Basketball, baseball, or football?",
"Can you lick your elbow?",
"Can you see yourself being married to the creepiest kid a your school someday?",
"Can you speak a different language?",
"Can you touch your tongue to your nose?",
"Can you use a pogo stick?",
"Could you go a week without junk food?",
"Could you go two months without talking to your friends?",
"Could you go two months without talking to your friends?",
"Describe the most attractive thing about each person in this room.",
"Describe the person of your dreams.",
"Describe the strangest dream you've ever had. Did you like it?",
"Describe the weirdest dream you've ever had?",
"Describe the weirdest dream you’ve ever had?",
"Describe what makes someone husband or wife material.",
"Describe your most recent dream that you recall",
"Describe your perfect date.",
"Did you have an imaginary friend growing up?",
"Did your parents ever give you the 'birds and the bees' talk?",
"Do you believe in love at all?",
"Do you believe in love at first sight?",
"Do you cover your eyes during a scary parts of a movie?",
"Do you dance when you’re by yourself?",
"Do you drool in your sleep?",
"Do you ever apply makeup without using the mirror?",
"Do you ever talk to yourself in the mirror?",
"Do you ever talk to yourself in the mirror?",
"Do you ever try to solve the problems between your best friend and his/her crush?",
"Do you frequently stalk anyone on social media? Who?",
"Do you go directly to your home after college in the evening?",
"Do you have a hidden talent? What is it?",
"Do you have a job? If so, what is your favourite thing about it?",
"Do you have a job? If so, what is your favourite thing about it?",
"Do you have a security blanket?",
"Do you have an imaginary friend?",
"Do you have any phobias?",
"Do you have any silly nicknames?",
"Do you have any unusual talents?",
"Do you have bad foot odor?",
"Do you have crush on any of your school teachers?",
"Do you know how to cook?",
"Do you know how to dance?",
"Do you lick your plate?",
"Do you like doing chores?",
"Do you like hanging out with your parents?",
"Do you like parties?",
"Do you like to exercise?",
"Do you message people during your classes?",
"Do you own a pair of footie pajamas?",
"Do you prefer apple or android?",
"Do you sing in the shower? What song did you sing the last time?",
"Do you sing in the shower?",
"Do you sleep with a stuffed animal?",
"Do you still take bubble baths?",
"Do you talk in your sleep?",
"Do you think you will marry your bf/gf? If not, why not?",
"Do you think you'll marry your current partner?",
"Do you think {name} is cute?",
"Do you want to get married one day?",
"Do you want to have kids? How many?",
"Do you write in a diary?",
"Explain to the person you like least in this group why you like them the least",
"Has your partner ever embarrassed you?",
"Have you been in any fights while in school?",
"Have you ever accidentally hit something with your car?",
"Have you ever admired your best friend if he/she get good marks in the examination?",
"Have you ever been caught checking someone out?",
"Have you ever been late to class?",
"Have you ever bitten a toenail?",
"Have you ever blamed a fart on an animal?",
"Have you ever blamed something that you have done on one of your siblings?",
"Have you ever blamed something that you have done on one of your siblings?",
"Have you ever cheated on a test?",
"Have you ever cheated on a test?",
"Have you ever cheated on any test?",
"Have you ever cheated on your partner?",
"Have you ever cheated or been cheated on?",
"Have you ever climbed a tree?",
"Have you ever crapped your pants since you were a child?",
"Have you ever cried because you missed your parents so much?",
"Have you ever cursed at your parents? Why?",
"Have you ever eaten food that you've dropped on the ground? If so, how long was it on the ground?",
"Have you ever eaten lunch by yourself? Why?",
"Have you ever eaten something off the floor?",
"Have you ever failed a class?",
"Have you ever fallen asleep during a class?",
"Have you ever fallen asleep in class?",
"Have you ever farted and then blamed someone else?",
"Have you ever farted in an elevator and get caught?",
"Have you ever farted loudly in public?",
"Have you ever flirted with your teacher in the school for good marks and grades?",
"Have you ever got caught doing something you shouldn’t?",
"Have you ever gotten detention or been suspended?",
"Have you ever gotten into a fight on school grounds?",
"Have you ever gotten mad at a friend for posting an unflattering picture of you?",
"Have you ever had a crush on a teacher? Who?",
"Have you ever had a crush on a teacher?",
"Have you ever had a crush on a teacher?",
"Have you ever had a crush on someone that your best friend has dated?",
"Have you ever had a crush on someone that your best friend has dated?",
"Have you ever had someone write an assignment or a work for you?",
"Have you ever had the crush on someone much younger or older than you? What’s the biggest age difference?",
"Have you ever kept a library book?",
"Have you ever let someone take the blame for something you did?",
"Have you ever lied to your best friend?",
"Have you ever lied to your parents about if you were in classes or not?",
"Have you ever lied to your parents about what you were doing after school?",
"Have you ever lied to your parents about what you were doing after school?",
"Have you ever peed in a pool?",
"Have you ever peed in the pool?",
"Have you ever played Cards Against Humanity with your parents?",
"Have you ever posted something on social media that you regret?",
"Have you ever posted something on the internet/social media that you regret?",
"Have you ever pretended to be sick to get out of something? If so, what was it?",
"Have you ever pretended to like a gift? How did you pretend?",
"Have you ever pulled a prank on one of your teachers?",
"Have you ever pulled a prank on your teacher?",
"Have you ever received a love letter?",
"Have you ever regretted something you did to get a crush's attention?",
"Have you ever ridden the bus without paying the fare?",
"Have you ever sent someone the wrong text?",
"Have you ever stolen something of value worth more than $10?",
"Have you ever stolen something?",
"Have you ever stuck gum under a desk?",
"Have you ever taken money from your roommate?",
"Have you ever taken money that didn't belong to you?",
"Have you ever tasted a booger?",
"Have you ever thought about cheating on your partner?",
"Have you ever thrown a party at your house?",
"Have you ever told a lie during a game of Truth or Dare? What was it and why?",
"Have you ever told one of your best friend's secrets, even if you said you wouldn't?",
"Have you ever told one of your best friend’s secrets, even if you said you wouldn’t?",
"Have you ever tried to sing a tongue twister in a musical way?",
"Have you ever used self tanner?",
"Have you ever used someone else's password?",
"Have you ever walked in on your parents doing it?",
"Have you ever walked into a wall?",
"Have you ever watched a movie you knew you shouldn’t?",
"Have you ever watched an adult film without your parents knowing?",
"Have you ever waved at someone thinking they saw you when really they didn't? What did you do when you realized it?",
"Have you ever worn the same clothes for more than three days?",
"Have you got a secret talent?",
"How about prettiest eyes?",
"How do you feel about end pieces of a loaf of bread?",
"How do you feel about social media?",
"How far would you go to land the guy or girl of your dreams?",
"How far would you go to land the guy or girl of your dreams?",
"How flexible are you?",
"How long have you gone without a shower?",
"How long have you gone without brushing your teeth?",
"How many boyfriends (or girlfriends) have you had?",
"How many days could you go without your partner?",
"How many hours do you exercise a day?",
"How many hours would you spend online if you didn't have school or homework?",
"How many kids would you like to have?",
"How many pancakes have you eaten in a single sitting?",
"How many partners have you had?",
"How many selfies do you take a day?",
"How many siblings do you have?",
"How many times have you skipped class for no reason?",
"How old were you when your parents sat you down for 'the talk' and what did they say (or not say) about 'the birds and the bees'?",
"How soon did you realize that you were in love with your partner?",
"How soon did/do you want start a family?",
"How tall do you want to be?",
"How was your first kiss?",
"How would you rate your looks on a scale of 1 to 10?",
"If someone offered you $1 million dollars to break up with your partner, would you do it?",
"If there was no such thing as money, what would you do with your life?",
"If we didn't have a dress code, what would you wear to school that you can't wear now?",
"If you could be a superhero; what would your power be?",
"If you could be any animal, which one would you be?",
"If you could be any dinosaur; which would it be?",
"If you could be any super villain; who would you be?",
"If you could be reincarnated into anyone's body, who would you want to become?",
"If you could change one thing on your body, what would it be?",
"If you could date anyone in the world, who would you date?",
"If you could dye your hair any colour, what colour would you pick?",
"If you could erase one past experience, what would it be?",
"If you could go anywhere in the world, where would you go?",
"If you could go back in time in erase one thing you said or did, what would it be?",
"If you could go on a romantic date with anyone in this room, who would you pick?",
"If you could have one celebrity follow you on Instagram, who would that be?",
"If you could have one physical feature of someone in this room, what would that be?",
"If you could make $1 million, would you drop out of school?",
"If you could make one wish right this second, what would it be?",
"If you could only hear one song for the rest of your life, what would it be?",
"If you could only hear one song for the rest of your life, what would it be?",
"If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?",
"If you could only use one swear word for the rest of your life, which one would you choose?",
"If you could own your own business one day, what would it be?",
"If you could own your own business one day, what would it be?",
"If you could own your own business one day; what would it be?",
"If you could plan a class prank knowing you'll never get caught, what would the prank be?",
"If you could play a prank on anyone without getting caught, who would you play it on?",
"If you could spend every waking moment with your partner, would you?",
"If you could suddenly become invisible, what would you do?",
"If you could switch lives with any celebrity for a day, who would it be?",
"If you could take away one bad thing in the world, what would it be?",
"If you could, what would you change about your life?",
"If you don't have one yet, where would you want to work?",
"If you had never met your partner, where do you think you would be?",
"If you had nine lives, what would you do that you wouldn't do now?",
"If you had the choice to live on your own right now, would you do it?",
"If you had the choice to live on your own right now, would you do it?",
"If you had the power to fire one teacher, who would it be?",
"If you had the power to fire one teacher, who would that be?",
"If you had to delete one app from your phone, what would it be?",
"If you had to marry someone in this room, who would it be?",
"If you had to take a person from another grade to prom, who would that be?",
"If you had to take one class for the rest of your life, what class would it be and who would the teacher be?",
"If you have ever cheated, why did you do it?",
"If you lost one day of your life every time you said a swear word, would you try not to do it?",
"If you ran out of toilet paper, would you consider wiping with the empty roll?",
"If you suddenly had a million dollars; what would you do with all of your money?",
"If you switched genders for the day, what would you do?",
"If you wanted to start your own business, what it would be?",
"If you were a billionaire, what would you spend your time doing?",
"If you were a billionaire, what would you spend your time doing?",
"If you were allowed to marry more than one person, would you? Who would you choose to marry?",
"If you were home by yourself all day, what would you do?",
"If you were reborn, what decade would you want to be born in?",
"If you were rescuing everyone here from a burning building, but you had to leave one behind, who would it be?",
"If you were rescuing people from a burning building and you had to leave one person behind from here, who would it be?",
"If you were to be stuck on a deserted island, which friend would you want with you?",
"If you were to be trapped on an island for 3 days, what would you take with you?",
"If you were trapped for three days on an island, who are three people in this room you would bring with you and why?",
"If your car broke down in the middle of the road, who in this room would be the last person you would call? Why?",
"If your parents forced you to leave home, where would you go?",
"If your partner broke up with you at school, what would you do?",
"Is it better to use shampoo as soap or soap as shampoo?",
"Of the people at our school, who do you think would make the best president?",
"Of the people here, who do you want to trade lives with?",
"Of the people in this group, who are you the most jealous of?",
"Of the people in this group, who do you disagree with most frequently?",
"Of the people in this group, who do you most want to switch lives with and why?",
"Of the people in this group, who would you feel most comfortable with naked?",
"Of the people in this room, who would you go out with?",
"Pick one person from this room you'd like to exchange your partners with!",
"Rate me on a scale of 1 to 10, with 10 being the hottest.",
"Say one positive and one negative thing about each person here.",
"Suppose you were a billionaire, how would you spend your time?",
"Talk about about the last time someone unexpectedly walked in on you while you were naked",
"Talk about about your most awkward date",
"Talk about the best vacation you've ever been on?",
"Tell me your weirdest habit.",
"Tell us about a time you embarrassed yourself in front of a crush.",
"Tell us about your most embarrassing vomit story",
"Tell us about your your first kiss",
"The world ends next week and you can do anything you want. What would you do?",
"True or false? You have a crush on {name}.",
"What animal most closely resembles your eating style?",
"What app on your phone do you waste the most time on?",
"What app on your phone do you waste the most time on?",
"What are the three qualities you feel are most important in a friend?",
"What are you most excited about?",
"What are you most self-conscious about?",
"What are your must have future wife/husband qualities",
"What are your three favourite colours, and why?",
"What attracts you to a person of the opposite sex?",
"What celebrity are you obsessed with?",
"What celebrity are you obsessed with?",
"What children’s movie could you watch over and over again?",
"What college do you plan on going to?",
"What country would like to live in if you had the chance?",
"What did you learn in school that you wish you could forget?",
"What do most of your friends think about you that is totally untrue?",
"What do you daydream about the most?",
"What do you do when you are alone at home?",
"What do you like most and least about your own appearance?",
"What do you like most and least about your personality?",
"What do you really hope your parents never find out about you?",
"What do you think is better: tests or essays?",
"What do you think is your biggest fear?",
"What do you think is your biggest flaw?",
"What do you think is your biggest insecurity?",
"What do you think is your biggest strength?",
"What do you think is your biggest weakness?",
"What does your dream boy or girl look like?",
"What does your favorite pajamas look like?",
"What don't you like about me?",
"What has been the most embarrassing moment you've experienced so far?",
"What have you seen that you wish you could unsee?",
"What is one disturbing fact I should know about you?",
"What is one embarrassing fact about you?",
"What is one lie your partner/best friend tells everyone else, but you know the truth?",
"What is one misconception about you?",
"What is one thing that you've always wanted to do?",
"What is one thing you wish people knew about you?",
"What is something childish that you still do?",
"What is something that no one else knows about you?",
"What is something that people think you would never do but you have?",
"What is something that you have never told anyone?",
"What is something you're glad your parents don't know about you?",
"What is something you’ve done to try to be 'cooler'?",
"What is something you’ve done to try to be ‘cooler’?",
"What is the best vacation you’ve ever been on?",
"What is the biggest lie you've ever told without getting caught?",
"What is the biggest romantic fail you've ever experienced?",
"What is the biggest secret you've ever kept from your parents?",
"What is the craziest thing that you have ever done without your parents knowing?",
"What is the craziest thing you've ever done to attract a crush?",
"What is the cruelest thing you've ever done to a friend?",
"What is the first thing you'd do if you woke up one day and you were the opposite sex?",
"What is the funniest youtube video you have ever seen?",
"What is the longest that you have ever been without taking a shower?",
"What is the longest time that you think you could go without the internet?",
"What is the longest time that you think you could go without your cell phone?",
"What is the longest time that you think you could go without your smartphone?",
"What is the longest time you have ever been grounded?",
"What is the longest time you have ever been grounded?",
"What is the longest you have gone without sleep?",
"What is the meanest thing you've ever said to someone?",
"What is the most annoying thing that one of your siblings has done?",
"What is the most annoying thing that your siblings do?",
"What is the most attractive feature on a person?",
"What is the most awkward experience you've had with a crush?",
"What is the most childish thing that you still do?",
"What is the most childish thing you still do?",
"What is the most disgusting habit of yours?",
"What is the most disgusting thing you've ever done?",
"What is the most embarrassing moment in your life?",
"What is the most embarrassing nickname you have ever had?",
"What is the most embarrassing photo you have on your phone?",
"What is the most embarrassing thing in your web browser history (Assume you've never had Incognito mode on.)?",
"What is the most embarrassing thing you have put up on social media?",
"What is the most embarrassing thing your parents have caught you doing?",
"What is the most evilest thing you've ever done?",
"What is the most expensive thing you have stolen?",
"What is the most expensive thing you own?",
"What is the most expensive thing you own?",
"What is the most flirtatious thing you've ever done?",
"What is the most food you’ve eaten in a single sitting?",
"What is the most illegal thing you have ever done?",
"What is the most useless piece of knowledge you know?",
"What is the silliest thing you have an emotional attachment to?",
"What is the stupidest thing that you've done in front of a crowd?",
"What is the stupidest thing you have ever done?",
"What is the weirdest thing that your parents have caught you doing?",
"What is the weirdest thing you've done when you were alone?",
"What is the weirdest thing you've ever done in front of the mirror?",
"What is the wildest thing you have ever done in your life so far?",
"What is your best talent?",
"What is your biggest fear in a relationship?",
"What is your biggest fear?",
"What is your biggest pet peeve?",
"What is your biggest pet peeve?",
"What is your biggest regret?",
"What is your biggest turn off in a partner?",
"What is your deepest darkest fear?",
"What is your dream job?",
"What is your dream wedding?",
"What is your favorite villain character?",
"What is your favourite TV show?",
"What is your favourite animal?",
"What is your favourite game to play?",
"What is your favourite holiday and why?",
"What is your favourite kind of clothing?",
"What is your favourite kind of clothing?",
"What is your favourite movie?",
"What is your favourite place to go out to eat?",
"What is your favourite school subject?",
"What is your favourite season of the year?",
"What is your favourite song that is out right now?",
"What is your favourite song that is out right now?",
"What is your favourite song?",
"What is your favourite sport?",
"What is your favourite sports team?",
"What is your favourite sports team?",
"What is your favourite thing about your partner?",
"What is your favourite thing to do after school?",
"What is your favourite thing to do on the weekends?",
"What is your favourite vegetable?",
"What is your favourite way of getting attention from the opposite sex?",
"What is your go-to song for the shower?",
"What is your greatest fear in a relationship?",
"What is your guilty pleasure?",
"What is your guilty pleasure?",
"What is your partner's most annoying habit?",
"What is your real GPA?",
"What is your shoe size?",
"What is your weirdest habit?",
"What is your worst habit?",
"What personality trait does you least like about your partner/best friend?",
"What prejudice do you secretly harbour?",
"What secret about yourself did you tell someone in confidence and then they told a lot of other people?",
"What song on the radio do you sing with every time it comes on?",
"What terrible thing have you done that you lied to cover up?",
"What the biggest deal breaker for you?",
"What was a rumor that went around about you?",
"What was the best day of your life?",
"What was the biggest mistake of your life?",
"What was the cruelest joke you ever played on someone?",
"What was the last lie that you told your best friend?",
"What was the last rate-R movie you watched?",
"What was the last thing you ate?",
"What was the last thing you searched for on your phone?",
"What was the last thing you texted?",
"What was the most awkward romantic encounter you have had?",
"What was the strangest dream you have ever had?",
"What was the worst encounter you had with a police officer?",
"What was the worst score you’ve ever gotten on a test?",
"What was your childhood ambition?",
"What was your childhood nickname?",
"What was your first impression of your partner?",
"What was your first job?",
"What was your funniest first date ever?",
"What was your most embarrassing moment in public?",
"What was your partner's childhood nickname?",
"What was your scariest nightmare?",
"What would be in your web history that you’d be embarrassed if someone saw?",
"What would be the worst part about getting pantsed in front of your crush?",
"What would you do if you found out you flunked school?",
"What would you do if you were invisible for a day?",
"What would you do if you were the opposite sex for a month?",
"What would you do if your parents left the house to you for a whole week?",
"What would you do if your parents left the house to you for a whole week?",
"What ‘As seen on TV’ product do you secretly want to buy?",
"What's one food that you will never order at a restaurant?",
"What's one thing you do that you don't want anyone to know about?",
"What's one thing you would never do in front of someone you had a crush on?",
"What's one thing you would never eat on a first date?",
"What's the best thing to say to your friend that would be the worst thing to say to your crush?",
"What's the craziest thing that you have ever done without your parents knowing?",
"What's the craziest thing you've done while under the influence?",
"What's the first thing you would do if you woke up one day as the opposite sex?",
"What's the longest time you've stayed in the bathroom, and why did you stay for that long?",
"What's the most embarrassing thing you've ever done in front of a teacher?",
"What's the most unflattering school picture of you?",
"What's the most useless piece of knowledge you know?",
"What's the worst class to have first period?",
"What's the worst weather to be stuck outside in if all you could wear was a bathing suit?",
"What's you dream job?",
"What's your biggest fear about college?",
"What's your biggest pet peeve?",
"When did you learn how to ride a bike?",
"When was the first time you fell in love and with whom?",
"When was the last time you brushed your teeth?",
"When was the last time you cried?",
"When was the last time you shit yourself?",
"When was the last time you were flat-out rejected and how did you handle it?",
"When was the last time you wet the bed?",
"When was the last time you wet the bed?",
"When was the most inappropriate time you farted?",
"Which celebrity would you like to a date?",
"Who do you admire the most?",
"Who do you like the least here and why?",
"Who do you think is the Beyonce of the group?",
"Who do you think is the cutest person in our class?",
"Who do you think is the hottest celebrity?",
"Who do you think is the worst dressed person here?",
"Who do you think you act more like, your father or your mother?",
"Who has the best dance moves?",
"Who has the best smile?",
"Who has the cutest nose?",
"Who have you loved but they didn't love you back?",
"Who here do you think is the best flirt?",
"Who here knows something about you that you wouldn't want revealed?",
"Who in this room would be the worst person to date? Why?",
"Who is most important to you?",
"Who is one person you pretend to like, but actually don’t?",
"Who is the best roommate that you have ever had?",
"Who is the most annoying person among your friends?",
"Who is the most annoying person you know?",
"Who is the most annoying person you know?",
"Who is the person you most regret kissing?",
"Who is the person you're in love with?",
"Who is the sexiest person in this room?",
"Who is the worst teacher you have ever had, why?",
"Who is the worst teacher you have ever had, why?",
"Who is the worst teacher you have ever had; why?",
"Who is your best friend?",
"Who is your best looking teacher that you have ever had?",
"Who is your crush at school?",
"Who is your crush?",
"Who is your favourite Disney character?",
"Who is your favourite friend?",
"Who is your favourite in-law?",
"Who is your favourite person and why?",
"Who is your favourite singer?",
"Who is your favourite teacher, and why?",
"Who is your favourite? Mom or Dad?",
"Who is your least favourite in-law?",
"Who is your secret crush?",
"Who is/was your celebrity crush?",
"Who taught you how to tie your shoes?",
"Who would you ask to prom if you could choose anyone?",
"Who would you never ever want to sit next to in class?",
"Who would you take to prom?",
"Who's the funniest in this room?",
"Who's the most annoying person in this room?",
"Whom would you love to date amongst the people in this room?",
"Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
"Would you drop out of school if you were to win the lottery?",
"Would you ever be mean to someone if it meant you could save your close friend from embarrassment?",
"Would you ever consider being a nudist?",
"Would you ever date two people at once if you could get away with it?",
"Would you ever get into a long distance relationship?",
"Would you ever get on a dating website?",
"Would you ever get on a dating website?",
"Would you have voted for or against Trump?",
"Would you leave your partner if it meant that you would be very rich?",
"Would you rather eat dog food or cat food?",
"Would you rather live with no internet or no A/C or heating?",
"Would you rather not shower for a month, or eat the same meal everyday for a month?",
"Would you trade in your dog for a million dollars?",
"Would you want your best friend to go to the same college as you?",
"Would you want your current partner to go to the same college as you?",
"Would you wear your shirt inside out for a whole day if someone paid you $100?",
"Would your partner trade you for a million dollars?",
"You have to delete 5 people on Instagram. Name them.",
"You have to delete every app on your except for five. Name the five you would keep.",
"Your house is burning down and you have to get out fast. You can take one thing with you, what would it be?",
"You’re in a public restroom and just went #2, then you realized your stall has no toilet paper. What do you do?"]